/**
 * Load the managed label set into D1.
 *
 *   node --env-file-if-exists=.env worker/backfill-labels.js --out worker/labels.sql
 *   cd worker && npx wrangler d1 execute nh-dashboard --remote --file labels.sql
 *
 * Separate from the commit backfill on purpose, and not because of the size —
 * twenty rows against fifteen thousand. They run on different clocks. Commit
 * history needs topping up when the store falls behind; this needs re-running
 * when somebody edits a file in a different repo, which is an event nothing
 * here can observe. Folding it into a long sweep would mean either running the
 * long sweep to change a colour, or letting the palette rot between runs.
 *
 * This is the one input in the store that is neither a webhook payload nor
 * derived from one. GitHub sends no event when Label-Sync-GTNH's config
 * changes, because the dashboard does not watch that repo — and a Worker
 * cannot go and read it either. So it is pushed in from outside, by this.
 *
 * Deletions are handled: labels removed from the config are removed here, in
 * the same transaction, because `byLabel` reads this table as the definitive
 * list and a label nobody manages any more should not keep its column.
 */

import { createWriteStream } from "node:fs";

import { fetchManagedLabelDetails } from "../src/github/labelSync.js";
import { LABEL_SOURCE } from "../src/config.js";

const args = new Map();
for (let i = 2; i < process.argv.length; i++) {
  const arg = process.argv[i];
  if (!arg.startsWith("--")) continue;
  const [key, inline] = arg.slice(2).split("=");
  const next = process.argv[i + 1];
  if (inline !== undefined) args.set(key, inline);
  else if (next && !next.startsWith("--")) args.set(key, process.argv[++i]);
  else args.set(key, true);
}

const OUT = args.get("out") ?? "worker/labels.sql";

function q(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

async function main() {
  const { owner, repo, path } = LABEL_SOURCE;
  console.log(`\nReading labels from ${owner}/${repo}/${path}\n`);

  const labels = await fetchManagedLabelDetails();

  const withColour = labels.filter((l) => l.color).length;
  console.log(`  ${labels.length} labels, ${withColour} with a colour`);
  if (withColour < labels.length) {
    console.warn(
      `  ${labels.length - withColour} have no colour and will render uncoloured`,
    );
  }

  const out = createWriteStream(OUT);
  out.write(`-- Generated by worker/backfill-labels.js on ${new Date().toISOString()}\n`);
  out.write(`-- ${labels.length} labels from ${owner}/${repo}\n\n`);

  const names = labels.map((l) => q(l.name)).join(", ");

  // Delete first, in the same file. wrangler applies a file atomically, so the
  // table is never briefly empty for a reader — and a label dropped from the
  // config loses its column rather than lingering as a stale one.
  out.write(`DELETE FROM labels WHERE name NOT IN (${names});\n\n`);

  out.write(
    "INSERT INTO labels (name, color, description, position) VALUES\n" +
      labels
        .map((l) => `  (${q(l.name)}, ${q(l.color)}, ${q(l.description)}, ${l.position})`)
        .join(",\n") +
      "\nON CONFLICT (name) DO UPDATE SET" +
      " color = excluded.color," +
      " description = excluded.description," +
      " position = excluded.position;\n",
  );

  await new Promise((resolve) => out.end(resolve));

  console.log(
    `\n  wrote ${OUT}\n\n` +
      `  npx wrangler d1 execute nh-dashboard --remote --file ${OUT.replace(/^worker\//, "")}\n` +
      `  (run from the worker/ directory)\n`,
  );
}

main().catch((err) => {
  // No fallback list, and no partial file. See fetchManagedLabelDetails: writing
  // the three-name fallback into D1 would replace the org's real label set with
  // an invented one, and nothing downstream could tell.
  console.error(`\n  failed: ${err.message}\n  D1 keeps whatever it already had.\n`);
  process.exit(1);
});
